### ISSUE TITLE
Published APIs are invisible in Publisher or Store after Publisher/Store pod recreate

### ISSUE THREAD

**Issue by anupbansal** [wso2/kubernetes-apim#197]
**Description:**
After the WSO2 Kubernetes setup is up and running and APIs are published and subscribed, the APIs are not visible again in the Publisher or Store, after the Publisher or Store deployment is recreated. When the PODs are reinitialized, error is reported saying that an API definition is present in the DB but not synced. 

`[2019-05-30`` 13:47:22,498]  INFO - AndesContextInformationManager Binding Sync [create]: [Binding]E=amq.topic/Q=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-65f6b94b98-6r28c/10.233.90.29/RK=throttledata/D=false/EX=true
[2019-05-30 13:47:22,508]  WARN - AndesSubscriptionManager Subscriptions are not in sync. Subscription not available in subscription registry but is in DB. Thus adding subscription to registry=subscriptionId=d696b7b6-3b9e-4b70-8e3c-5480c21c4c4c,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-65f6b94b98-6r28c/10.233.90.29,protocolType=AMQP,isActive=true,connection= [ connectedIP=/10.233.90.29:38544/1,connectedNode=NODE:wso2apim-gateway-deployment-65f6b94b98-6r28c/10.233.90.29,protocolChannelID=8ad11394-ce42-49b1-9dba-c0a81426f313] `

Looks like the queue names are bound to POD IPs which are dynamic in nature in a Kubernetes setup causing the issue. What changes are required in the configuration to solve this.

wso2apim-gateway-deployment-6d8c484cdb-lphq8

**Suggested Labels:**

**Suggested Assignees:**

**WSO2 2.6.0**

**Ubuntu**    

**Steps to reproduce:**
1. Setup the WSO2 environment on Kubernetes.
2. Publish and subscribe new APIs
3. Destroy the Publisher/Store deployment and recreate it

**Comment by anupbansal** [comment]
Logs when issue occurred again:
`[2019-06-24 19:29:14,362]  INFO - InboundDBSyncRequestEvent Running DB sync task.
[2019-06-24 19:29:15,761]  WARN - InboundDBSyncRequestEvent Recovering node. Adding queue to queue registry queueName=AMQP_Topic_throttledata_NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212,queueOwner=clientid,isExclusive=true,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-06-24 19:29:15,773]  INFO - AndesContextInformationManager Queue Sync [create]: AMQP_Topic_throttledata_NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212
[2019-06-24 19:29:15,774]  WARN - InboundDBSyncRequestEvent Recovering node. Adding queue to queue registry queueName=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211,queueOwner=clientid,isExclusive=true,isDurable=false,isShared=false,lastPurgedTimestamp=0
[2019-06-24 19:29:15,801]  INFO - AndesContextInformationManager Queue Sync [create]: AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211
[2019-06-24 19:29:15,815]  WARN - InboundDBSyncRequestEvent Recovering node. Adding binding [Binding]E=amq.topic/Q=AMQP_Topic_throttledata_NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212/RK=throttledata/D=false/EX=true
[2019-06-24 19:29:15,818]  INFO - AndesContextInformationManager Binding Sync [create]: [Binding]E=amq.topic/Q=AMQP_Topic_throttledata_NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212/RK=throttledata/D=false/EX=true
[2019-06-24 19:29:15,818]  WARN - InboundDBSyncRequestEvent Recovering node. Adding binding [Binding]E=amq.topic/Q=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211/RK=throttledata/D=false/EX=true
[2019-06-24 19:29:15,826]  INFO - AndesContextInformationManager Binding Sync [create]: [Binding]E=amq.topic/Q=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211/RK=throttledata/D=false/EX=true
[2019-06-24 19:29:15,834] ERROR - AndesSubscriptionManager Could not add subscription: subscriptionId=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122,protocolType=AMQP,isActive=true,subscriberConnection=Y29ubmVjdGVkSVA9LzEwLjIzMy45MS4xMjI6NjA3NjAvMSxjb25uZWN0ZWROb2RlPU5PREU6d3NvMmFwaW0tZ2F0ZXdheS1kZXBsb3ltZW50LTZkOGM0ODRjZGItc2N4OG4vMTAuMjMzLjkxLjEyMixwcm90b2NvbENoYW5uZWxJRD0zNzhmY2ViMi0yYzM3LTQxMDQtOGIwZS0wNThjMTM1NmViNTE=
org.wso2.andes.kernel.subscription.SubscriptionException: StorageQueue: AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122 is not registered while creating subscription id=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3
        at org.wso2.andes.kernel.subscription.AndesSubscription.<init>(AndesSubscription.java:136)
        at org.wso2.andes.kernel.subscription.AndesSubscriptionManager.reloadSubscriptionsFromStorage(AndesSubscriptionManager.java:921)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadSubscriptions(InboundDBSyncRequestEvent.java:208)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:76)
        at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-06-24 19:29:15,841] ERROR - AndesSubscriptionManager Could not add subscription: subscriptionId=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122,protocolType=AMQP,isActive=true,subscriberConnection=Y29ubmVjdGVkSVA9LzEwLjIzMy45MS4xMjI6NjA3NjAvMSxjb25uZWN0ZWROb2RlPU5PREU6d3NvMmFwaW0tZ2F0ZXdheS1kZXBsb3ltZW50LTZkOGM0ODRjZGItc2N4OG4vMTAuMjMzLjkxLjEyMixwcm90b2NvbENoYW5uZWxJRD0zNzhmY2ViMi0yYzM3LTQxMDQtOGIwZS0wNThjMTM1NmViNTE=
org.wso2.andes.kernel.subscription.SubscriptionException: StorageQueue: AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122 is not registered while creating subscription id=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3
        at org.wso2.andes.kernel.subscription.AndesSubscription.<init>(AndesSubscription.java:136)
        at org.wso2.andes.kernel.subscription.AndesSubscriptionManager.reloadSubscriptionsFromStorage(AndesSubscriptionManager.java:972)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadSubscriptions(InboundDBSyncRequestEvent.java:208)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:76)
        at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[2019-06-24 19:29:15,843]  WARN - AndesSubscriptionManager Subscriptions are not in sync. Subscription not available in subscription registry but is in DB. Thus adding subscription to registry=subscriptionId=db6bd56e-3aa6-4657-bf5f-6f6e396bf2c9,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211,protocolType=AMQP,isActive=true,connection= [ connectedIP=/10.233.91.211:47636/1,connectedNode=NODE:wso2apim-gateway-deployment-6d8c484cdb-lphq8/10.233.91.211,protocolChannelID=35ced1e4-d172-4eac-9b28-113c17a33e2c ]
[2019-06-24 19:29:15,844]  WARN - AndesSubscriptionManager Subscriptions are not in sync. Subscription not available in subscription registry but is in DB. Thus adding subscription to registry=subscriptionId=b1557b1f-c540-48ba-b37f-e532bdbc7db6,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212,protocolType=AMQP,isActive=true,connection= [ connectedIP=/10.233.91.212:46000/1,connectedNode=NODE:wso2apim-km-deployment-9db5b4b44-rnn94/10.233.91.212,protocolChannelID=2b602130-6f51-4f27-90a4-247090aa33f7 ]
[2019-06-24 19:29:15,848] ERROR - AndesSubscriptionManager Could not add subscription: subscriptionId=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3,storageQueue=AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122,protocolType=AMQP,isActive=true,subscriberConnection=Y29ubmVjdGVkSVA9LzEwLjIzMy45MS4xMjI6NjA3NjAvMSxjb25uZWN0ZWROb2RlPU5PREU6d3NvMmFwaW0tZ2F0ZXdheS1kZXBsb3ltZW50LTZkOGM0ODRjZGItc2N4OG4vMTAuMjMzLjkxLjEyMixwcm90b2NvbENoYW5uZWxJRD0zNzhmY2ViMi0yYzM3LTQxMDQtOGIwZS0wNThjMTM1NmViNTE=
org.wso2.andes.kernel.subscription.SubscriptionException: StorageQueue: AMQP_Topic_throttledata_NODE:wso2apim-gateway-deployment-6d8c484cdb-scx8n/10.233.91.122 is not registered while creating subscription id=73cdf203-7514-4f4d-a06a-3d7a4c3e41b3
        at org.wso2.andes.kernel.subscription.AndesSubscription.<init>(AndesSubscription.java:136)
        at org.wso2.andes.kernel.subscription.AndesSubscriptionManager.reloadSubscriptionsFromStorage(AndesSubscriptionManager.java:1002)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.reloadSubscriptions(InboundDBSyncRequestEvent.java:208)
        at org.wso2.andes.kernel.disruptor.inbound.InboundDBSyncRequestEvent.updateState(InboundDBSyncRequestEvent.java:76)
        at org.wso2.andes.kernel.disruptor.inbound.InboundEventContainer.updateState(InboundEventContainer.java:268)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:70)
        at org.wso2.andes.kernel.disruptor.inbound.StateEventHandler.onEvent(StateEventHandler.java:40)
        at com.lmax.disruptor.BatchEventProcessor.run(BatchEventProcessor.java:128)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)`

This is quite a serious issue as all the APIs are no longer visible in Publisher or Store.

**Comment by anupbansal** [comment]
Issue is resolved now. I was working with my own setup of pattern-3 before this was released. I was using a shared Carbon DB setup across all the distributed components. Following the instructions in the WSO2 documentation helped resolve the issue

**Comment by gs-offcl** [comment]
Could u pls provide the right configs to store/persist published apis to file system(NAS) ? 
I have used pattern_1 helm charts with below configuration - apacheSolrIndexing disabled in deployment.toml. The apim uses WSO2AM_DB and WSO2_SHARED_DB as backend databases for users and shared.

deployment.toml
===========
{{ if .Values.wso2.deployment.persistentRuntimeArtifacts.apacheSolrIndexing.enabled }}
    [database.local]
    url = "jdbc:h2:/home/wso2carbon/solr/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"

    [indexing]
    location = "/home/wso2carbon/solr/indexed-data"
    {{ else }}
    [database.local]
    url = "jdbc:h2:./repository/database/WSO2CARBON_DB;DB_CLOSE_ON_EXIT=FALSE"
    {{ end }}

Appreciate any help..Thanks.

**Comment by gs-offcl** [comment]
Also, one strange issue - the apis which are published by super tenant (carbon.super) are persisted in backend(file system) store and not tenant level published apis and these tenant level published apis are lost when apim restarts..

**Comment by pubudu538** [comment]
If you are having tenants, then you need to mount the tenant folder as well. https://apim.docs.wso2.com/en/3.2.0/install-and-setup/setup/single-node/configuring-an-active-active-deployment/#step-5-configure-the-artifact-synchronization

**Comment by gs-offcl** [comment]
We have mounted tenants folder and its working now.

<APIM_HOME>/repository/tenants

Thanks
