### ISSUE TITLE
Analytics-Dashboard failing to connect to APIM in semi distributed setup

### ISSUE THREAD

**Issue by invent360** [wso2/kubernetes-apim#313]
**Description:**
Setting up a cluster of APIM components such that APIM Gateway, Publisher, DevPortal and Key Manager are in one node and Analytics in another node. Analytics Dashboard comes up but fails to load Analytics data from APIM with the following errors
![Screenshot 2020-01-05 at 00 44 30](https://user-images.githubusercontent.com/46233704/71773419-ac23b100-2f54-11ea-8521-864209eab44d.png)

**Suggested Labels:**

**wso2 apim 3.0.0**

**Kubernetes (Docker Desktop)**    

**Steps to reproduce:**

**Related Issues:**

**Comment by abhi1git** [comment]
I have deployed pattern-1 wso2 helm chart on my kubernetes cluster running on AWS. Added ingress with our public domain so as to access dashboard and api manager over the internet.
Getting error in dashboard portal in APIM Developer Portal. I have attached all the required screenshots and logs here. **Can you please let me know what configuration change is required to overcome the error Access Denied to data provider.**

Current Configuration- 1 instance 1 worker 
```
NAME                                                              READY   STATUS    RESTARTS   AGE
wso2-nfs-server-provisioner-0                                     1/1     Running   0          105m
wso2am-mysql-db-service-c8b47bb5b-697lx                           1/1     Running   0          105m
wso2am-pattern-1-am-1-deployment-0                                1/1     Running   0          105m
wso2am-pattern-1-am-analytics-dashboard-deployment-7cf7646ps2zh   1/1     Running   0          105m
wso2am-pattern-1-am-analytics-worker-deployment-6988f7456dw749r   1/1     Running   0          105m

```


Error logs-
```
> ubuntu@ubuntu:~/CI-CD/charts/stable$ kubectl logs pod/wso2am-pattern-1-am-analytics-dashboard-deployment-7cf7646ps2zh -n wso2
> Copying critical patch fixes to GA pack
> JAVA_HOME environment variable is set to /opt/java/openjdk
> CARBON_HOME environment variable is set to /home/wso2carbon/wso2am-analytics-3.1.0
> RUNTIME_HOME environment variable is set to /home/wso2carbon/wso2am-analytics-3.1.0/wso2/dashboard
> [2020-05-14 13:52:12,437]  INFO {org.wso2.carbon.launcher.extensions.OSGiLibBundleDeployerUtils updateOSGiLib} - Successfully updated the OSGi bundle information of Carbon Runtime: dashboard  
> osgi> [2020-05-14 13:52:14,746]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /websocket-provider/{topic}
> [2020-05-14 13:52:15,540]  INFO {org.wso2.msf4j.internal.websocket.WebSocketServerSC} - All required capabilities are available of WebSocket service component is available.
> [2020-05-14 13:52:15,565]  INFO {org.wso2.carbon.metrics.core.config.model.JmxReporterConfig} - Creating JMX reporter for Metrics with domain 'org.wso2.carbon.metrics'
> [2020-05-14 13:52:15,595]  INFO {org.wso2.msf4j.analytics.metrics.MetricsComponent} - Metrics Component is activated
> [2020-05-14 13:52:15,639]  INFO {org.wso2.carbon.databridge.agent.internal.DataAgentDS} - Successfully deployed Agent Server 
> [2020-05-14 13:52:15,694]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
> [2020-05-14 13:52:15,773]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9092
> [2020-05-14 13:52:15,774]  INFO {org.wso2.transport.http.netty.contractimpl.listener.ServerConnectorBootstrap$HttpServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 9643
> [2020-05-14 13:52:16,294]  INFO {org.wso2.msf4j.internal.websocket.EndpointsRegistryImpl} - Endpoint Registered : /data-provider
> [2020-05-14 13:52:16,393]  INFO {org.wso2.carbon.analytics.idp.client.core.utils.IdPServiceUtils} - IdP client of type 'apim' is started.
> [2020-05-14 13:52:16,706]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiverServiceComponent} - org.wso2.carbon.databridge.receiver.binary.internal.Service Component is activated
> [2020-05-14 13:52:16,727]  INFO {org.wso2.carbon.databridge.receiver.thrift.internal.ThriftDataReceiverDS} - Service Component is activated
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by org.wso2.msf4j.util.RuntimeAnnotations (file:/home/wso2carbon/wso2am-analytics-3.1.0/wso2/lib/plugins/msf4j-core_2.7.7.jar) to constructor sun.reflect.annotation.AnnotationInvocationHandler(java.lang.Class,java.util.Map)
> WARNING: Please consider reporting this to the maintainers of org.wso2.msf4j.util.RuntimeAnnotations
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> [2020-05-14 13:52:16,890]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'business-rules' is available at 'https://100.105.246.148:9643/business-rules'.
> [2020-05-14 13:52:16,926]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'analytics-dashboard' is available at 'https://100.105.246.148:9643/analytics-dashboard'.
> [2020-05-14 13:52:17,012]  INFO {org.wso2.carbon.dashboards.core.internal.DashboardImporter} - Successfully imported dashboard 'apimadmin' from '/home/wso2carbon/wso2am-analytics-3.1.0/wso2/dashboard/resources/dashboards/apimadmin.json'.
> [2020-05-14 13:52:17,080]  INFO {org.wso2.carbon.dashboards.core.internal.DashboardImporter} - Successfully imported dashboard 'apimpublisher' from '/home/wso2carbon/wso2am-analytics-3.1.0/wso2/dashboard/resources/dashboards/apimpublisher.json'.
> [2020-05-14 13:52:17,115]  INFO {org.wso2.carbon.dashboards.core.internal.DashboardImporter} - Successfully imported dashboard 'apimdevportal' from '/home/wso2carbon/wso2am-analytics-3.1.0/wso2/dashboard/resources/dashboards/apimdevportal.json'.
> [2020-05-14 13:52:17,488]  INFO {org.wso2.carbon.uiserver.internal.deployment.listener.AppTransportBinder} - Web app 'policies' is available at 'https://100.105.246.148:9643/policies'.
> [2020-05-14 13:52:17,491]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 API Manager Analytics Server started in 5.684 sec
> [2020-05-14 13:52:18,077]  INFO {org.wso2.callhome.internal.CallHome} - 
> .......................................................................
> There are 3 updates available for the product 'wso2am-analytics-3.1.0'.
> .......................................................................
> [2020-05-14 13:52:50,370] ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error occurred while authorizing the access to data provider. SiddhiStoreDataProvider. Access denied to data provider. java.lang.Exception: Access denied to data provider.
> 	at org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint.onMessage(DataProviderEndPoint.java:154)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.executeMethod(MSF4JWSConnectorListener.java:360)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.lambda$handleTextWebSocketMessage$18(MSF4JWSConnectorListener.java:196)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.handleTextWebSocketMessage(MSF4JWSConnectorListener.java:177)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.onMessage(MSF4JWSConnectorListener.java:85)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.DefaultWebSocketConnectorFuture.notifyWebSocketListener(DefaultWebSocketConnectorFuture.java:52)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.notifyTextMessage(WebSocketInboundFrameHandler.java:203)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.channelRead(WebSocketInboundFrameHandler.java:158)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
> 	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
> [2020-05-14 13:52:50,373] ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error found in method : java.lang.Exception: Access denied to data provider.
> [2020-05-14 13:53:50,364] ERROR {org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint} - Error occurred while authorizing the access to data provider. SiddhiStoreDataProvider. Access denied to data provider. java.lang.Exception: Access denied to data provider.
> 	at org.wso2.carbon.data.provider.endpoint.DataProviderEndPoint.onMessage(DataProviderEndPoint.java:154)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.executeMethod(MSF4JWSConnectorListener.java:360)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.lambda$handleTextWebSocketMessage$18(MSF4JWSConnectorListener.java:196)
> 	at java.base/java.util.Optional.ifPresent(Optional.java:183)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.handleTextWebSocketMessage(MSF4JWSConnectorListener.java:177)
> 	at org.wso2.msf4j.internal.MSF4JWSConnectorListener.onMessage(MSF4JWSConnectorListener.java:85)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.DefaultWebSocketConnectorFuture.notifyWebSocketListener(DefaultWebSocketConnectorFuture.java:52)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.notifyTextMessage(WebSocketInboundFrameHandler.java:203)
> 	at org.wso2.transport.http.netty.contractimpl.websocket.WebSocketInboundFrameHandler.channelRead(WebSocketInboundFrameHandler.java:158)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
> 	at io.netty.handler.codec.http.websocketx.Utf8FrameValidator.channelRead(Utf8FrameValidator.java:77)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:323)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:297)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1476)
> 	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1225)
> 	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1272)
> 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502)
> 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441)
> 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:337)
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1408)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359)
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:345)
> 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
> 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:677)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
> 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
> 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
> 	at java.base/java.lang.Thread.run(Thread.java:834)
> 
```



![Analytics-Dashboard-Error](https://user-images.githubusercontent.com/35002471/81955216-6fb14180-9627-11ea-8ca6-3a7664bc1ccb.png)


![Console-page](https://user-images.githubusercontent.com/35002471/81955218-70e26e80-9627-11ea-8c66-63a9a9551a68.png)


![Network-page](https://user-images.githubusercontent.com/35002471/81955220-717b0500-9627-11ea-8d77-ad00ae9263b0.png)


![Request-page](https://user-images.githubusercontent.com/35002471/81955223-72139b80-9627-11ea-8e2d-0b7e5f25168d.png)
