### ISSUE TITLE
Database Connectivity Issue

### ISSUE THREAD

**Issue by imesh** [wso2/kubernetes-apim#34]
The following errors were noticed in the Analytics node, may be max_connections might need to be increased with MySQL 5.7:

2017-09-12 20:06:17,503] ERROR {org.wso2.carbon.registry.core.config.RegistryContext} -  Unable to get instance of the registry context
--
  | org.wso2.carbon.registry.core.exceptions.RegistryException: Unable to connect to Data Source
  | at org.wso2.carbon.registry.core.config.RegistryConfigurationProcessor.populateRegistryConfig(RegistryConfigurationProcessor.java:165)
  | at org.wso2.carbon.registry.core.config.RegistryContext.<init>(RegistryContext.java:462)
  | at org.wso2.carbon.registry.core.config.RegistryContext.<init>(RegistryContext.java:443)
  | at org.wso2.carbon.registry.core.config.RegistryContext.getBaseInstance(RegistryContext.java:322)
  | at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.getEmbeddedRegistryService(RegistryCoreServiceComponent.java:587)
  | at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.buildRegistryService(RegistryCoreServiceComponent.java:520)
  | at org.wso2.carbon.registry.core.internal.RegistryCoreServiceComponent.activate(RegistryCoreServiceComponent.java:126)
  | at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  | at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.eclipse.equinox.internal.ds.model.ServiceComponent.activate(ServiceComponent.java:260)
  | at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.activate(ServiceComponentProp.java:146)
  | at org.eclipse.equinox.internal.ds.model.ServiceComponentProp.build(ServiceComponentProp.java:345)
  | at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponent(InstanceProcess.java:620)
  | at org.eclipse.equinox.internal.ds.InstanceProcess.buildComponents(InstanceProcess.java:197)
  | at org.eclipse.equinox.internal.ds.Resolver.getEligible(Resolver.java:343)
  | at org.eclipse.equinox.internal.ds.SCRManager.serviceChanged(SCRManager.java:222)
  | at org.eclipse.osgi.internal.serviceregistry.FilteredServiceListener.serviceChanged(FilteredServiceListener.java:107)
  | at org.eclipse.osgi.framework.internal.core.BundleContextImpl.dispatchEvent(BundleContextImpl.java:861)
  | at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
  | at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:148)
  | at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEventPrivileged(ServiceRegistry.java:819)
  | at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.publishServiceEvent(ServiceRegistry.java:771)
  | at org.eclipse.osgi.internal.serviceregistry.ServiceRegistrationImpl.register(ServiceRegistrationImpl.java:130)
  | at org.eclipse.osgi.internal.serviceregistry.ServiceRegistry.registerService(ServiceRegistry.java:214)
  | at org.eclipse.osgi.framework.internal.core.BundleContextImpl.registerService(BundleContextImpl.java:433)
  | at org.wso2.carbon.user.core.internal.Activator.startDeploy(Activator.java:69)
  | at org.wso2.carbon.user.core.internal.BundleCheckActivator.start(BundleCheckActivator.java:61)
  | at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
  | at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
  | at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
  | at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
  | at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
  | at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
  | at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
  | at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
  | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
  | at com.mysql.jdbc.Util.getInstance(Util.java:408)
  | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:918)
  | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:897)
  | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:886)
  | at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:860)
  | at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2104)
  | at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2029)
  | at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:779)
  | at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
  | at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
  | at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
  | at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
  | at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
  | at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:389)
  | at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
  | at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:278)
  | at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:182)
  | at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:701)
  | at org.apache.tomcat.jdbc.pool.ConnectionPool.borrowConnection(ConnectionPool.java:635)
  | at org.apache.tomcat.jdbc.pool.ConnectionPool.getConnection(ConnectionPool.java:188)
  | at org.apache.tomcat.jdbc.pool.DataSourceProxy.getConnection(DataSourceProxy.java:127)
  | at org.wso2.carbon.registry.core.config.RegistryConfigurationProcessor.populateRegistryConfig(RegistryConfigurationProcessor.java:149)
  | ... 43 more
  | Caused by: com.mysql.jdbc.exceptions.jdbc4.CommunicationsException: Communications link failure

**Comment by pubudu538** [comment]
Hi Imesh,

I checked again pattern-1 with mysql 5.7.19 and did not encounter this issue. Based on the stack trace it looks like a connection issue. This could occur if the mysql server does not start prior to analytics node. Are you getting this error continuously?

Thank you!
Pubudu.

**Comment by imesh** [comment]
I investigated this with Pubudu and found that this issue has occurred due to the MySQL Connector version (v5.1.43) I used. Switched v5.1.34 and the problem solved.
