### ISSUE TITLE
Too many services&applications (BinaryDataReceiver , CEP, WSO2 Message Broker,  ...) are started in apim-gw-worker POD for 2.1.0/pattern-2 

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#41]
Hi,

A Gateway worker (https://docs.wso2.com/display/AM210/Product+Profiles) : Only starts the components related to the API Gateway.
You use this when the API Gateway acts as a worker node in a cluster. This profile starts the backend features for data processing and communicating with the manager node.

In analyzing the trace I find that many services are started.

......
[2017-09-16 04:59:26,556]  INFO - ManagementModeConfigurationLoader CEP started in Single node mode
[2017-09-16 04:59:26,626]  INFO - TemplateDeployerServiceTrackerDS Successfully deployed the execution manager tracker service
[2017-09-16 04:59:32,688]  INFO - BinaryDataReceiver Started Binary SSL Transport on port : 9711
[2017-09-16 04:59:32,690]  INFO - BinaryDataReceiver Started Binary TCP Transport on port : 9611
[2017-09-16 04:59:32,709]  INFO - DataBridgeDS Successfully deployed Agent Server 
[2017-09-16 04:59:33,280]  INFO - EmbeddedRegistryService Configured Registry in 216ms
.....
......
[2017-09-16 05:00:56,576]  INFO - Andes Starting Safe Zone Calculator for slots.
[Broker] BRK-1002 : Starting : Listening on TCP port 5672
[2017-09-16 05:00:56,624]  INFO - listening [Broker] BRK-1002 : Starting : Listening on TCP port 5672
[Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8672
[2017-09-16 05:00:56,628]  INFO - listening [Broker] BRK-1002 : Starting : Listening on TCP/SSL port 8672
[Broker] BRK-1004 : Qpid Broker Ready
[2017-09-16 05:00:56,632]  INFO - MessagingEngine Starting SlotDelivery Workers.
[2017-09-16 05:00:56,635]  INFO - MessagingEngine Start Disruptor writing messages to store.
.......
.......
[2017-09-16 05:00:56,699]  INFO - QpidServiceComponent AMQP Host Address : 0.0.0.0 Port : 5672
[2017-09-16 05:00:56,699]  INFO - QpidServiceComponent Successfully connected to AMQP server on port 5672
[2017-09-16 05:00:56,700]  WARN - QpidServiceComponent MQTT Transport is disabled as per configuration.
[2017-09-16 05:00:56,700]  INFO - QpidServiceComponent WSO2 Message Broker is started.
.......
[2017-09-16 05:00:58,453]  INFO - ThriftDataReceiver Thrift Server started at 0.0.0.0
....
[2017-09-16 05:00:58,509]  INFO - ThriftDataReceiver Thrift SSL port : 7711
.....
[2017-09-16 05:00:58,547]  INFO - ThriftDataReceiver Thrift port : 7611
.......
[2017-09-16 05:00:59,011]  INFO - TaskServiceImpl Task service starting in STANDALONE mode...
[2017-09-16 05:00:59,392] ERROR - SourceHandler I/O error: Received fatal alert: unknown_ca
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
.....
.....
[2017-09-16 05:00:59,530]  INFO - RegistryEventingServiceComponent Successfully Initialized Eventing on Registry
[2017-09-16 05:00:59,900]  INFO - JMXServerManager JMX Service URL  : service:jmx:rmi://localhost:11111/jndi/rmi://localhost:9999/jmxrmi
[2017-09-16 05:00:59,904]  INFO - StartupFinalizerServiceComponent Server           :  WSO2 API Manager-2.1.0
[2017-09-16 05:00:59,905]  INFO - StartupFinalizerServiceComponent WSO2 Carbon started in 104 sec
[2017-09-16 05:01:00,188]  INFO - CarbonUIServiceComponent Mgt Console URL  : https://X.X.X.X:9443/carbon/
[2017-09-16 05:01:00,188]  INFO - CarbonUIServiceComponent API Publisher Default Context : https://X.X.X.X:9443/publisher
[2017-09-16 05:01:00,188]  INFO - CarbonUIServiceComponent API Store Default Context : https://X.X.X.X:9443/store
[2017-09-16 05:01:00,329]  WARN - JMSListener Polling tasks on destination : throttleData of type topic for listener Siddhi-JMS-Consumer#throttleData have not yet started after 3 seconds ..
[2017-09-16 05:01:02,974] ERROR - SourceHandler I/O error: Received fatal alert: unknown_ca
javax.net.ssl.SSLException: Received fatal alert: unknown_ca
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1666)
	at sun.security.ssl.SSLEngineImpl.fatal(SSLEngineImpl.java:1634)
	at sun.security.ssl.SSLEngineImpl.recvAlert(SSLEngineImpl.java:1800)
.....
.....

This will probably correct : https://github.com/wso2/kubernetes-apim/issues/40

Thanks,
Youcef HILEM

**Comment by yhilem** [comment]
I just analyzed the pattern-6 configuration implemented with puppet (https://github.com/wso2/puppet-apim/blob/master/wso2am_runtime/hieradata/dev/wso2/wso2am_runtime/pattern-6/gateway-worker.yaml).

There is indeed removal of all unnecessary applications:

wso2::remove_file_list:
   -  "repository/deployment/server/jaggeryapps"
   -  "repository/deployment/server/webapps/am#sample#calculator#v1.war"
   -  "repository/deployment/server/webapps/api#am#admin#v0.11.war"
   -  "repository/deployment/server/webapps/api#am#publisher#v0.11.war"
   -  "repository/deployment/server/webapps/api#am#store#v0.11.war"
   -  "repository/deployment/server/webapps/authenticationendpoint.war"
   -  "repository/deployment/server/webapps/client-registration#v0.11.war"
   -  "repository/deployment/server/webapps/oauth2.war"
   -  "repository/deployment/server/webapps/shindig.war"
   -  "repository/deployment/server/webapps/throttle#data#v1.war"

And some services are disabled : 

wso2::enable_thrift_server: false
wso2::thrift_server_host: localhost
wso2::key_validator_client_type: WSClient
wso2::disable_jms_event_parameters: true
wso2::apply_gateway_specific_configurations: true
wso2::enable_log_analyzer: true


Thanks,
Youcef HILEM

**Comment by yhilem** [comment]
See : https://github.com/wso2/kubernetes-apim/issues/40
