### ISSUE TITLE
Docker image for analytics exposes wrong ports  (9763 9443 5672 9711 9611 7711 7611 ) instead of (9764 9444 5672 9712 9612 7712 7612)

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#42]
Hi,

Ports exposed in docker image (7711 7611) (https://github.com/wso2/kubernetes-apim/blob/2.1.0/base/analytics/Dockerfile#L95) for thrift  doesn't match POD targetport (7712 7612) for wso2apim-analytics-1-deployment (https://github.com/wso2/kubernetes-apim/blob/2.1.0/pattern-2/artifacts/apim-analytics/wso2apim-analytics-1-deployment.yaml#L46) & wso2apim-analytics-2-deployment

Thus, these exception are thrown :

[2017-09-16 22:10:03,190] ERROR - DataEndpointConnectionWorker Error while trying to connect to ssl://wso2apim-analytics-1:7712
org.wso2.carbon.databridge.agent.exception.DataEndpointSecurityException: Error while trying to connect to ssl://wso2apim-analytics-1:7712
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:81)
	at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:91)
	at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.thrift.transport.TTransportException: Could not connect to wso2apim-analytics-1 on port 7712
	at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:237)
	at org.apache.thrift.transport.TSSLTransportFactory.getClientSocket(TSSLTransportFactory.java:169)
	at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:63)
	... 9 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:427)
	at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
	at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:233)
	... 11 more

.........

Thanks,
Youcef HILEM

**Comment by yhilem** [comment]
Not a bug : https://docs.wso2.com/display/AM210/Default+Product+Ports

I have confused with the ports exposed by WSO2-EI Analytics profile: https://github.com/wso2/kubernetes-ei/blob/master/dockerfiles/analytics/Dockerfile

**Comment by yhilem** [comment]
Hi,

Now I am confident that this is a configuration error.

Here is the trace of POD wso2apim-analytics-2:
....
[2017-09-17 11:42:22,902]  INFO {org.wso2.carbon.event.processor.manager.commons.transport.server.TCPEventServer} -  EventServer starting event listener on 172.30.213.129:11225
[2017-09-17 11:42:22,903] ERROR {org.wso2.carbon.event.processor.manager.core.internal.EventHandler} -  Unable to start TCPEventServer for EventReceiver started on port 11225
[2017-09-17 11:42:22,985]  INFO {org.wso2.carbon.event.template.manager.core.internal.ds.TemplateDeployerServiceTrackerDS} -  Successfully deployed the execution manager tracker service
[2017-09-17 11:42:28,298]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary SSL Transport on port : 9712
[2017-09-17 11:42:28,300]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary TCP Transport on port : 9612
[2017-09-17 11:42:28,343]  INFO {org.wso2.carbon.databridge.core.internal.DataBridgeDS} -  Successfully deployed Agent Server 
....
[2017-09-17 11:43:05,455]  INFO {org.wso2.carbon.core.transports.http.HttpTransportListener} -  HTTP port        : 9764
[2017-09-17 11:43:05,456]  INFO {org.wso2.carbon.core.transports.http.HttpsTransportListener} -  HTTPS port       : 9444
....
[2017-09-17 11:43:23,290]  INFO {org.jaggeryjs.jaggery.app.mgt.TomcatJaggeryWebappsDeployer} -  Deployed webapp: StandardEngine[Catalina].StandardHost[localhost].StandardContext[/portal].File[/home/o2_adm/wso2am-analytics-2.1.0/repository/deployment/server/jaggeryapps/portal]
[2017-09-17 11:43:23,526]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} -  Thrift Server started at 0.0.0.0
[2017-09-17 11:43:23,691]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} -  Thrift SSL port : 7712
[2017-09-17 11:43:23,747]  INFO {org.wso2.carbon.databridge.receiver.thrift.ThriftDataReceiver} -  Thrift port : 7612

Analytics/Dockerfile (https://github.com/wso2/kubernetes-apim/blob/2.1.0/base/analytics/Dockerfile)
# expose ports
EXPOSE 9763 9443 5672 9711 9611 7711 7611 11225 10006 11001 11501 8082 4041

Thus, we have exceptions like this 


[2017-09-17 12:11:47,789] ERROR - DataEndpointConnectionWorker Error while trying to connect to ssl://wso2apim-analytics-2:7712
--
  | org.wso2.carbon.databridge.agent.exception.DataEndpointSecurityException: Error while trying to connect to ssl://wso2apim-analytics-2:7712
  | at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:81)
  | at org.wso2.carbon.databridge.agent.client.AbstractClientPoolFactory.makeObject(AbstractClientPoolFactory.java:39)
  | at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1212)
  | at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.connect(DataEndpointConnectionWorker.java:91)
  | at org.wso2.carbon.databridge.agent.endpoint.DataEndpointConnectionWorker.run(DataEndpointConnectionWorker.java:42)
  | at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  | at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  | at java.lang.Thread.run(Thread.java:745)
  | Caused by: org.apache.thrift.transport.TTransportException: Could not connect to wso2apim-analytics-2 on port 7712
  | at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:237)
  | at org.apache.thrift.transport.TSSLTransportFactory.getClientSocket(TSSLTransportFactory.java:169)
  | at org.wso2.carbon.databridge.agent.endpoint.thrift.ThriftSecureClientPoolFactory.createClient(ThriftSecureClientPoolFactory.java:63)
  | ... 9 more
  | Caused by: java.net.ConnectException: Connection refused (Connection refused)
  | at java.net.PlainSocketImpl.socketConnect(Native Method)
  | at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
  | at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
  | at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
  | at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
  | at java.net.Socket.connect(Socket.java:589)
  | at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
  | at sun.security.ssl.SSLSocketImpl.<init>(SSLSocketImpl.java:427)
  | at sun.security.ssl.SSLSocketFactoryImpl.createSocket(SSLSocketFactoryImpl.java:88)
  | at org.apache.thrift.transport.TSSLTransportFactory.createClient(TSSLTransportFactory.java:233)
  | ... 11 more


...................
The export should look like this
# expose ports
EXPOSE 9764 9444 5672 9712 9612 7712 7612 11225 10006 11001 11501 8082 4041

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

I have updated the analytics dockerfile with the relevant ports. Thank you for pointing this. According to error logs, I suspect that analytics server has not started at this moment.

https://github.com/wso2/kubernetes-apim/blob/2.1.0-nfs/base/analytics/Dockerfile#L95

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Hi Pubudu,

The platform is almost stable (I modified the ports), except for a few exceptions in the analytics module. 
I have to make sure before returning to you that it is not a config error on my part.

Thank,
Youcef HILEM
