### ISSUE TITLE
Errors in starting server, when passwords are encrypted with secure vault

### ISSUE THREAD

**Issue by yhilem** [wso2/kubernetes-apim#50]
Error in starting server, when passwords are encrypted with secure vault

[2017-10-07 11:29:43,754]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Starting WSO2 Carbon...
[2017-10-07 11:29:43,756]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Operating System : Linux 3.10.0-514.21.1.el7.x86_64, amd64
[2017-10-07 11:29:43,756]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Home        : /home/o2_adm/java/jre
[2017-10-07 11:29:43,756]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Version     : 1.8.0_121
[2017-10-07 11:29:43,757]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java VM          : Java HotSpot(TM) 64-Bit Server VM 25.121-b13,Oracle Corporation
[2017-10-07 11:29:43,757]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Carbon Home      : /home/o2_adm/wso2am-analytics-2.1.0
[2017-10-07 11:29:43,758]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  Java Temp Dir    : /home/o2_adm/wso2am-analytics-2.1.0/tmp
[2017-10-07 11:29:43,759]  INFO {org.wso2.carbon.core.internal.CarbonCoreActivator} -  User             : 1001580000, en-US, Etc/UTC
[2017-10-07 11:29:44,380]  INFO {org.wso2.carbon.event.output.adapter.kafka.internal.ds.KafkaEventAdapterServiceDS} -  Successfully deployed the Kafka output event adaptor service
[2017-10-07 11:29:44,563] ERROR {org.wso2.carbon.event.processor.manager.core.internal.EventHandler} -  Unable to start TCPEventServer for EventReceiver started on port 11225
[2017-10-07 11:29:44,824]  INFO {org.wso2.carbon.event.template.manager.core.internal.ds.TemplateDeployerServiceTrackerDS} -  Successfully deployed the execution manager tracker service
[2017-10-07 11:29:45,876] FATAL {org.wso2.carbon.tomcat.internal.TomcatBundleActivator} -  Error while starting server NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
org.w3c.dom.DOMException: NOT_FOUND_ERR: An attempt is made to reference a node in a context where it does not exist.
	at org.apache.xerces.dom.AttributeMap.internalRemoveNamedItem(Unknown Source)
	at org.apache.xerces.dom.AttributeMap.removeNamedItem(Unknown Source)
	at org.wso2.carbon.tomcat.internal.ServerManager.init(ServerManager.java:106)
	at org.wso2.carbon.tomcat.internal.TomcatBundleActivator.start(TomcatBundleActivator.java:45)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl$1.run(BundleContextImpl.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.startActivator(BundleContextImpl.java:702)
	at org.eclipse.osgi.framework.internal.core.BundleContextImpl.start(BundleContextImpl.java:683)
	at org.eclipse.osgi.framework.internal.core.BundleHost.startWorker(BundleHost.java:381)
	at org.eclipse.osgi.framework.internal.core.AbstractBundle.resume(AbstractBundle.java:390)
	at org.eclipse.osgi.framework.internal.core.Framework.resumeBundle(Framework.java:1176)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:559)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.resumeBundles(StartLevelManager.java:544)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.incFWSL(StartLevelManager.java:457)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.doSetStartLevel(StartLevelManager.java:243)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:438)
	at org.eclipse.osgi.framework.internal.core.StartLevelManager.dispatchEvent(StartLevelManager.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:230)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:340)
[2017-10-07 11:29:47,466]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary SSL Transport on port : 9712
[2017-10-07 11:29:47,467]  INFO {org.wso2.carbon.databridge.receiver.binary.internal.BinaryDataReceiver} -  Started Binary TCP Transport on port : 9612

**Related Issues:**
https://wso2.org/jira/browse/CARBON-16104

Thanks,
Youcef HILEM

**Comment by pubudu538** [comment]
Hi Youcef,

Could you please try this in a WUM updated pack [1] ? The Same issue can be found in [2].

[1] - https://docs.wso2.com/display/ADMIN44x/Updating+WSO2+Products
[2] - https://wso2.org/jira/browse/CARBON-16116

Thank you!
Pubudu.

**Comment by yhilem** [comment]
Hi Pubudu,

I downloaded with WUM the updates for wso2am-2.1.0 and wso2am-analytics-2.1.0

We have not made any changes to the “<PRODUCT_HOME>/repository/deployment/server” directory.
And after parsing the diff files, I do not see any changes to the “<PRODUCT_HOME>/repository/conf” directory.
Under these conditions I will replace the two products by the two new ones and I will reconstruct new docker images. And deploy.

I also upgrade the jvm to jdk-8u144-linux-x64.tar.gz to use the Java SE support for Docker CPU and memory limits available since Java SE 8u131 (https://blogs.oracle.com/java-platform-group/java-se-support-for-docker-cpu-and-memory-limits). 

Thanks,
Youcef HILEM
