### ISSUE TITLE
SSL Certificate Key Alias Does Not Match

### ISSUE THREAD

**Issue by imesh** [wso2/kubernetes-apim#53]
**Description:**
The wso2carbon.jks file found in the base/analytics/files folder has used the key alias ```dockerapim``` and in the configurations the key alias has been specified as ```wso2carbon```.

**Affected Product Version:**
v2.1.0-2

**Steps to reproduce:**
1. Extract API-M Analytics 2.1.0 distribution.
2. Copy the wso2carbon.jks file found in base/analytics/files to ./repository/resources/security/ folder.
3. Start the API-M Analytics server, now the following error message will appear:

```
[2017-11-04 19:09:39,446] ERROR {org.wso2.carbon.analytics.spark.core.internal.AnalyticsComponent} -  Error initializing analytics executor: Cannot process Carbon datasources during Spark executor initialization: null
org.wso2.carbon.analytics.datasource.commons.exception.AnalyticsException: Cannot process Carbon datasources during Spark executor initialization: null
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.exportDataSourcesAsProperties(SparkAnalyticsExecutor.java:746)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.initializeSparkConf(SparkAnalyticsExecutor.java:578)
	at org.wso2.carbon.analytics.spark.core.internal.SparkAnalyticsExecutor.<init>(SparkAnalyticsExecutor.java:185)
	at org.wso2.carbon.analytics.spark.core.internal.AnalyticsComponent.activate(AnalyticsComponent.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

**Comment by pubudu538** [comment]
Solutions:

1. Update configuration files such as carbon.xml with dockerapim as the KeyAlias.
2. Replace the wso2carbon.jks which has wso2carbon as the keyalias.

Thank you!
