### ISSUE TITLE
SQL syntax error when listing Roles w/ LDAP User Store

### ISSUE THREAD

**Issue by HolySamosa** [wso2/kubernetes-apim#78]
**Description:**

When listing Roles in the admin console w/ LDAP Primary User Store, the UI reports the following error
```
Error while listing roles. Error is : You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near &#39;OPTION SQL_SELECT_LIMIT=DEFAULT&#39; at line 1
```

Logs:
```
[2018-04-06 23:42:24,278] ERROR - JDBCUserStoreManager Error while retrieving roles from Internal JDBC role store
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OPTION SQL_SELECT_LIMIT=100' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1031)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:957)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3376)
	<remaining stack trace omitted>
[2018-04-06 23:42:24,287] ERROR - DatabaseUtil Database error. Could not close statement. Continuing with others. - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OPTION SQL_SELECT_LIMIT=DEFAULT' at line 1
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'OPTION SQL_SELECT_LIMIT=DEFAULT' at line 1
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:406)
	at com.mysql.jdbc.Util.getInstance(Util.java:381)
	<remaining stack trace omitted>
```

**Steps to reproduce:**

Using tag `2.1.0-2` w/ images from docker.wso2.com.

* Installed using Openshift pattern-1 deployment.  
* Changed the Primary User Store to use `ReadOnlyLDAPUserStoreManager`,  using a `UserStoreManager` configuration that works without problem when tested w/ [wso2/docker-apim](https://github.com/wso2/docker-apim).
* List Roles in management console

**Comment by HolySamosa** [comment]
After rebuilding the images to include my certs, this problem has disappeared.  

My images use:
* mysql-connector-java-5.1.37-bin.jar
* jdk-8u121-linux-x64.tar.gz
* wso2am-2.1.0-update14.zip
